spring:
  application:
    name: crud # Nome da aplicação, usado para identificação em logs e monitoramento.
  datasource: # Configurações de conexão com o banco de dados.
    url: jdbc:mariadb://localhost:3306/student # URL de conexão para o banco MariaDB local na porta 3306.
    driver-class-name: org.mariadb.jdbc.Driver # Define o driver JDBC para MariaDB.
    username: root # Nome de usuário para conexão com o banco.
    password:  # Senha para conexão com o banco.
  jpa:
    hibernate:
      ddl-auto: update # Configura o Hibernate para atualizar o esquema do banco automaticamente.
    show-sql: true # Habilita a exibição das consultas SQL no console para depuração.
    database-platform: org.hibernate.dialect.MariaDBDialect